In [1]:
import pandas as pd

In [8]:
A = pd.read_csv('A_results.csv')
A

         name  optimal_value  best_value       time
0    A-n32-k5            784         901  17.953265
1    A-n33-k5            661         745  37.294832
2    A-n33-k6            742         826  24.273653
3    A-n34-k5            778         881  46.549175
4    A-n36-k5            799         930  46.719720
5    A-n37-k5            669         812  41.785697
6    A-n37-k6            949        1103  49.087185
7    A-n38-k5            730         922  44.653976
8    A-n39-k5            822        1038  20.685450
9    A-n39-k6            831        1024  55.035111
10   A-n44-k6            937        1235  10.939057
11   A-n45-k6            944        1298  18.427538
12   A-n45-k7           1146        1352  60.339010
13   A-n46-k7            914        1232  54.823709
14   A-n48-k7           1073        1465  53.824823
15   A-n53-k7           1010        1573  56.634160
16   A-n54-k7           1167        1626  51.261343
17   A-n55-k9           1073        1652  22.122528
18   A-n60-k9           1354        1851  55.297976
19   A-n61-k9           1034        1745  20.475992
20   A-n62-k8           1288        1880  54.080500
21   A-n63-k9           1616        2485  59.889047
22  A-n63-k10           1314        2070  22.962748
23   A-n64-k9           1401        2187  55.468045
24   A-n65-k9           1174        2252  22.800153
25   A-n69-k9           1159        2112  24.615578
26  A-n80-k10           1763        2913  24.988387

In [9]:
B = pd.read_csv('B_results.csv')
B

         name  optimal_value  best_value        time
0    B-n31-k5            672         704    7.967357
1    B-n34-k5            788         822   18.794473
2    B-n35-k5            955        1032  129.693909
3    B-n38-k6            805         828   22.499913
4    B-n39-k5            549         622  102.643930
5    B-n41-k6            829         979   21.827502
6    B-n43-k6            742         887  144.453960
7    B-n44-k7            909        1080  129.081343
8    B-n45-k5            751         894   17.842493
9    B-n45-k6            678         852  145.352809
10   B-n50-k7            741        1039  151.766310
11   B-n50-k8           1312        1511   19.439088
12   B-n51-k7           1032        1434  170.116518
13   B-n52-k7            747        1024  156.110897
14   B-n56-k7            707         897  156.238040
15   B-n57-k7           1153        1671  157.876073
16   B-n57-k9           1598        1909   20.592831
17  B-n63-k10           1496        2304   20.601909
18   B-n64-k9            861        1718  159.038723
19   B-n66-k9           1316        2081   22.928822
20  B-n67-k10           1032        1740   23.226283
21   B-n68-k9           1272        2037  160.071474
22  B-n78-k10           1221        2233  168.756675